-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'USER',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Assessment" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "date" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fullName" TEXT NOT NULL,
    "mobileNumber" TEXT,
    "moodChanges" TEXT NOT NULL,
    "optimismLevel" INTEGER NOT NULL,
    "currentEmotionalState" TEXT NOT NULL,
    "overthinking" TEXT NOT NULL,
    "socialFear" TEXT NOT NULL,
    "concentration" INTEGER NOT NULL,
    "socialInteraction" TEXT NOT NULL,
    "sleepPattern" TEXT NOT NULL,
    "reducedNeedForSleep" TEXT NOT NULL,
    "increasedEnergyLevel" TEXT NOT NULL,
    "suicidalThoughts" TEXT NOT NULL,
    "phq9Score" INTEGER NOT NULL,
    "anxiety7Score" INTEGER NOT NULL,
    "pastTrauma" TEXT NOT NULL,
    "intrusiveMemories" TEXT NOT NULL,
    "avoidanceBehaviour" TEXT NOT NULL,
    "familyStructure" TEXT NOT NULL,
    "familyDynamics" TEXT NOT NULL,
    "maritalAndFamilyConflict" TEXT NOT NULL,
    "financialStress" TEXT NOT NULL,
    "emotionalSupport" TEXT NOT NULL,
    "feelingOfLoneliness" TEXT NOT NULL,
    "feelingUnderstood" TEXT NOT NULL,
    "phq9_1" INTEGER NOT NULL,
    "phq9_2" INTEGER NOT NULL,
    "phq9_3" INTEGER NOT NULL,
    "phq9_4" INTEGER NOT NULL,
    "phq9_5" INTEGER NOT NULL,
    "phq9_6" INTEGER NOT NULL,
    "phq9_7" INTEGER NOT NULL,
    "phq9_8" INTEGER NOT NULL,
    "phq9_9" INTEGER NOT NULL,
    "gad7_1" INTEGER NOT NULL,
    "gad7_2" INTEGER NOT NULL,
    "gad7_3" INTEGER NOT NULL,
    "gad7_4" INTEGER NOT NULL,
    "gad7_5" INTEGER NOT NULL,
    "gad7_6" INTEGER NOT NULL,
    "gad7_7" INTEGER NOT NULL,
    "pitch" REAL NOT NULL,
    "pitchVariability" REAL NOT NULL,
    "speechRate" REAL NOT NULL,
    "pauseDuration" REAL NOT NULL,
    "voiceEnergy" REAL NOT NULL,
    "jitter" REAL NOT NULL,
    "shimmer" REAL NOT NULL,
    "hnr" REAL NOT NULL,
    "audioDisorder" TEXT NOT NULL,
    "audioConfidence" REAL NOT NULL,
    "tabularDisorder" TEXT NOT NULL,
    "finalDisorder" TEXT NOT NULL,
    "decision" TEXT NOT NULL,
    "allTabularPredictions" TEXT NOT NULL,
    "riskFlags" TEXT NOT NULL,
    "pdfReportName" TEXT,
    CONSTRAINT "Assessment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
